# Generated by Django 2.1.3 on 2018-12-28 10:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, help_text='Your birthday', null=True)),
                ('avatar', models.ImageField(blank=True, help_text='A profile image used to represent you! Pick something nice', upload_to='avatars/')),
                ('bio', models.CharField(blank=True, help_text='Tell us your life story', max_length=1000, validators=[django.core.validators.MinLengthValidator(10)])),
                ('location', models.CharField(blank=True, help_text='Where do you live?', max_length=100)),
                ('relationship', models.CharField(blank=True, help_text='Who are you seeing?', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
