# Generated by Django 2.1.3 on 2018-11-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='A profile image used to represent you! Pick something nice', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, help_text='Tell us your life story', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(help_text='Your birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Your email address', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Your given name', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Your surname', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='Where do you live?', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='relationship',
            field=models.CharField(blank=True, help_text='Who are you seeing?', max_length=100),
        ),
    ]
